version: '3.9'

services:
  backend:
    container_name: service-api
    image: service-api:latest
    environment:
      NRBESTAPI_VERSION: ${NRBESTAPI_VERSION}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      SERVICE_NAME: ${SERVICE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      KEYCLOAK_SERVER_REALM: ${KEYCLOAK_SERVER_REALM}
    hostname: service-api
    dns: 142.22.202.100
    ports:
      - "8090:8090"
    build:
      context: .
      dockerfile: Dockerfile
